application:
  hooks:
    post-app-build: mkdir -p dist/application/actions
  runtimeManifest:
    database:
      auto-provision: true
      region: amer
    packages: {}

extensions:
  # This extension is required for backend UI. Do not remove.
  commerce/backend-ui/1:
    $include: src/commerce-backend-ui-1/ext.config.yaml

  # This extension is required for business configuration. Do not remove.
  commerce/configuration/1:
    $include: src/commerce-configuration-1/ext.config.yaml

  # This extension is required for app management. Do not remove.
  commerce/extensibility/1:
    $include: src/commerce-extensibility-1/ext.config.yaml
